spring:
  application:
    name: eurekaclient
---
server:
  port: 8762
spring:
  profiles: client1
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
---
server:
  port: 8763
spring:
  profiles: client2
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/









