spring:
  application:
    name: eurekaserver
---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://peer1:8761/eureka/
#---
#server:
#  port: 8762
#spring:
#  profiles: peer2
#eureka:
#  instance:
#    hostname: peer2
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/